### ISSUE TITLE
Detect System Variables updates  even if string variable contains same string before

### ISSUE THREAD

**Issue by hmersch** [ioBroker/ioBroker.hm-rega#45]
HI all

A CCU String System variable, which is set to a string and set another time to the same(!) string, has a new timestamp in CCU but this is ignored by the Rega on iobroker.
All Timestamps in iobroker -> Objects -> Systemvariable -> MouseOver are left to the inital set of the variable

Sample: 
- System Variable "mytestvar" is set to "test". 
-> a 2nd setvalue by a ccu program to this variable with the same content "test" is ignored while setting it to "test2" would be detected (after next poll interval). 

I do expect that any variable change, which is indicated at the ccu i.e. by timestamp will also be detected by Rega and thus the iobroker->Objects would respect these new timestamps. 

UseCase: 
I use system Variable "LoggerMail" for incidating Log entries to be sent by email to me. 
When washer is ready LogggerMail is set to "Washer ready". If I start the washer another time before any other Message arrives on the variable, I will not be notified about the second finished washer run.

Thanks! ;-)

**Comment by foxriver76** [comment]
This behavior is designed by HomeMatic REGA itself. State changes of sys vars are pushed to ioB by REGA. So this issue has to be opened there if you desire this change.

**Comment by foxriver76** [comment]
My first look was wrong, I will look into it.

**Comment by hmersch** [comment]
Thanks in advance

**Comment by foxriver76** [comment]
Please test from GitHub ;-)

**Comment by hmersch** [comment]
Thanks - no luck till now. 

Updated from GitHub via ioBroker Admin - states that its 2,1.4 

No behaviour change in this direction. 
I have a testprogram setting LoggerMail variable to "test" and waited for couple of minutes - restarted the program. The Timestamp on the CCU is changing for the variable, but iobroker still is on the 1st timestamp. Reloading the objects, looking at the histpry values ... just the single entry with the 1st timestamp :-(

**Comment by Apollon77** [comment]
You did restart the instance after the GitHub update? You need to do this manually.

**Comment by foxriver76** [comment]
Please try again from GitHub, under some circumstances the timestamp was not detected, should be fixed now.

**Comment by hmersch** [comment]
Updated from Github again and restarted instance:

Sorry - still no luck. ioBroker->Objects Timestamps still showing the 1st change's timestamp while the timestamp in CCU is 3 min later and I waited much more than the 30sec of rega polling intervall

**Comment by foxriver76** [comment]
Hm.. also bei mir geht es. Ist dein Beispiel anders zu meinem?
![update](https://user-images.githubusercontent.com/25484431/51430637-80fa6180-1c1e-11e9-860b-0da2ba9f02ad.gif)

**Comment by foxriver76** [comment]
Also tested it with a String sys var and it worked.

**Comment by hmersch** [comment]
I do not see a significant difference - here is a record from my side.
Do you have any idea? 
![mycap-sysvarupdate](https://user-images.githubusercontent.com/971286/51437863-391e1d80-1ca4-11e9-8353-a330efec8406.gif)

**Comment by foxriver76** [comment]
Then lets have a look at the debug log when you do this. The answer to the polling script is logged on debug, like 

```

!# polling.fn 1.2 !# !# Dieses Script gibt die Werte aller Systemvariablen als J
--
2019-01-20 11:26:37.074  - debug: hm-rega.0 <-- {"1235":[false,"1970-01-01 01:00:00"],
"950":[true,"2019-01-19 19:06:23"],
"1947":[600.000000,"2019-01-20 11:25:00"],
"1372":[2.000000,"2019-01-20 11:24:00"],
"1399":[44.500000,"2019-01-20 11:25:00"],
"1874":[186.712000,"2019-01-20 11:25:00"],
"40":[0,"2019-01-12 16:43:25"],
"41":[0,"2019-01-20 11:26:14"]}

.
.
.

2019-01-20 11:27:07.037  - debug: hm-rega.0 --> polling.fn
2019-01-20 11:27:07.038  - debug: hm-rega.0 --> programs.fn
2019-01-20 11:27:07.042  - debug: hm-rega.0 --> !# polling.fn 1.2 !# !# Dieses Script gibt die Werte aller Systemvariablen als J
2019-01-20 11:27:07.058  - debug: hm-rega.0 <-- {"1235":[false,"1970-01-01 01:00:00"],
"950":[true,"2019-01-19 19:06:23"],
"1947":[600.000000,"2019-01-20 11:25:00"],
"1372":[2.000000,"2019-01-20 11:27:00"],
"1399":[44.500000,"2019-01-20 11:25:00"],
"1874":[186.712000,"2019-01-20 11:25:00"],
"40":[0,"2019-01-12 16:43:25"],
"41":[0,"2019-01-20 11:26:14"]}
```

here the timestamp should change when you set the same value again.

**Comment by hmersch** [comment]
- I downloaded the log via Admin of today after set LoggerMailDebug to Init than to TestSkript than to TestSkript again like in the animated gif before. 
- I seached for "44417" (the object id of LoggerMailDebug). 
- These are the last 3 occources in the log:

`
"44417":["Init","2019-01-20 11:42:43"],
"44417":["TestSkript","2019-01-20 11:42:59"],
"44417":["TestSkript","2019-01-20 11:43:21"],
`

So there the timestamp is changing ...

**Comment by foxriver76** [comment]
Also looks good. To make sure its not just an issue with admin (what I do not expect), you could run this script

```on({id: 'hm-rega.0.44417', change: 'any}, obj => {
     log('updated to ' + obj.state.val, 'warn');
}
```

otherwise I could introduce some logging to debug the problem, because I have no clue at the moment.

**Comment by foxriver76** [comment]
Yes it's correct, upload is also important after GitHub Installation, but normally only for changes which affect admin. So from console ``ìobroker upload hm-rega`` or via Admin GUI (available when expert mode activated by the red marked logo in screenshot)
![bildschirmfoto von 2019-01-20 12-30-31](https://user-images.githubusercontent.com/25484431/51438649-35dc5f00-1caf-11e9-974d-36f9c1c2416e.png) 

Important file is ``/opt/iobroker/node_modules/hm-rega/hm-rega.js``

**Comment by hmersch** [comment]
Yepp - now I have a 2.1.6 and used upload and rebooted (just to be sure). 

Now its working :-) 


THANK YOU SOOOOO MUCH! 
If we meet IRL you get a beer for sure! 

![mycap-history_success](https://user-images.githubusercontent.com/971286/51438861-00854080-1cb2-11e9-99c2-3fe9ef0a110c.PNG)

**Comment by foxriver76** [comment]
Perfect, you are welcome ;-)
