### ISSUE TITLE
Cannot select hm-rpc instance for other services than rfd

### ISSUE THREAD

**Issue by massa007** [ioBroker/ioBroker.hm-rega#78]
I wanted to enable the CUxD feature in my hm-rega.0 adapter. Unfortunately I can select my hm-rpc instance only for the rfd service. Everywhere else I can only select "none".

<img width="801" alt="Bildschirmfoto 2019-11-03 um 16 20 30" src="https://user-images.githubusercontent.com/16576171/68087422-e76f0a00-fe55-11e9-9782-a67071b8f6a9.png">

**Expected behavior**
I would expect to be able to select my existing instance like for rfd.

**Versions:**
 - hm-rpc version: 1.10.0
 - hm-rega version: 2.4.12
 - JS-Controller version: 1.5.11
 - Node version: v8.16.2 
 - Operating system: raspbian
 - CCU model: pivccu
 - CCU firmware: 3.47.15

**Comment by foxriver76** [comment]
I can reproduce it. Problem is a small bug in 1.10.0 which is fixed in 1.10.3. But wasn't aware of this side effect. So I will declare 1.10.3 as stable to get rid off it.

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/529

**Comment by massa007** [comment]
I do still have the problem after updating to version 1.10.3 !
Do you need any information?

**Comment by foxriver76** [comment]
Maybe you need to upload the adapter if you updated via GitHub installation. Also the hm-rpc adapter needs to be configured for CuxD.
